### PR TITLE
Some bug findings and a installation guide 

### PR DESCRIPTION
**Pull request by bornakke**
We now have a working copy of ANTA running here in Denmark and would like to contribute with the bugs we encountered and fixed during the journey, as well as a tested tutorial for other people to follow if they want to setup ANTA on their own server.

We are currently looking into fixing some more bugs, but they will be contributed in another pull request. 

Best regards
Tobias Bornakke

### CODE REVIEW

**Comment by danieleguido** [comment]
Hi Tobias,

thank you very much for your work, very much appreciated!

All the best,
Daniele

**Comment by bornakke** [comment]
No problems, glad that you could use the commitments :)

I have a specific project for which I would like to experiment with your upcoming hypertext tool. Do you think there is any chance that we could gain access to that tool? 

I have tried to install it myself, but the installation instruction appears to be out of date.

Best regards
Tobias

**Comment by boogheta** [comment]
Hello bornakke, HCI is still in development, a valid version with proper installation information should be released by the end of june, so I'd just recommand you wait a little bit :)

**Comment by bornakke** [comment]
Hi Booghta,

We couldn't wait any longer so I just spent the last week setting it up. And yesterday we finally got it to work. Have today made our first two serious crawls and no real bugs so far :)

But let me know if you want me to fill you in with bugs when I come around them?

Best Regards
Tobias

PS: I also made some english installations instruction as i went along (Ubuntu LAMP server), which I can sent to you to if they will be of any help to you.

PPS: And beautiful work by the way. HCI appears to be so much better than both navicrawler and issuecrawler.

**Comment by boogheta** [comment]
Tobias,
Great news! :)
Just, you should know that the entire code is being refactored and reorganised in different places at the moment, including the installation part. You're very welcome to send along your instructions though, even if I believe they won't really match the coming updated version :)
Also many more functionnalities aren't fully implemented yet and will come in the coming months.

I propose we switch to the issues of HCI now ;)

**Comment by bornakke** [comment]
Well what took me time was not really getting HCI to work, but rather to get the many server extensions needed for HCI to work. The final installation of HCI was simple in comparison to this. 

I will see you in the HCI issue area :)

**Pull request merged**
